### PR TITLE
Add improved CI

### LINKED ISSUE #6: Adding an improved CI
Hello Tom!
I am planning to contribute to your project(s).
How come that there are zero unit tests? I'm also missing hundreds of GitHub stars.

> Changing the world one line of code at a time.

### PR DESCRIPTION
**Pull request by szepeviktor**
🎁 This is my gift for Future Tom :)

kép

Closes #6

@betterthanclay

### CODE REVIEW

**Comment by szepeviktor** [comment]
🛡️ Please consider updating the badge in README.

**Comment by betterthanclay** [comment]
Hi Viktor, thanks for this, it looks great!

I'm just working through a bunch of updates on other packages then will merge this PR and apply it across all the other repos 👌

**Comment by betterthanclay** [comment]
> 🛡️ Please consider updating the badge in README.

What specifically needs updating? I'm open to suggestions 👍

**Comment by szepeviktor** [comment]
> > 🛡️ Please consider updating the badge in README.
> 
> What specifically needs updating? I'm open to suggestions 👍

#8 👀

**Comment by betterthanclay** [comment]
Oh yes, hah, forgot about that, thanks

**Comment by szepeviktor** [comment]
@betterthanclay Future Tom is already here? :)

**Comment by szepeviktor** [comment]
When there is no binary in the repo

`test "$(find . -type f -not -path './.git/*' -executable)" = ""`

this command checks for execute permissions, the lack of this permission.

**Comment by betterthanclay** [comment]
Thanks for this - I've applied it to all 27 current DL packages 👌

**Pull request merged**
